### PR TITLE
[point_cloud_aggregator] pointrow_step of tmp_output should depend on size of tmp_output

### PR DESCRIPTION
**Pull request by Timple**
We had a segfault using `point_cloud_aggregator`.

This patch fixed it.

### CODE REVIEW

**Comment by matlabbe** [comment]
That previous commit did try to fix this problem: https://github.com/introlab/rtabmap_ros/blame/e8edafb8ff713958620fd34eb98f7c113f845579/src/nodelets/point_cloud_aggregator.cpp#L295-L296

I would have expect that `output->row_step + cloud2->row_step = tmp_output->width * tmp_output->point_step` though maybe not always the case. It seems indeed safer to use the output width*point_step.

**Comment by Timple** [comment]
Cool! Thankyou

Since the last release was a couple of months ago, and the noetic-sync just happened, I hope this might be a good time to re-release the package :). So we can test it before the next sync.

**Comment by matlabbe** [comment]
Hi, 
I was waiting for a challenge to end this summer to push a new version, but I forgot. Here is the pull request for 0.20.14 on noetic: https://github.com/ros/rosdistro/pull/30893

Also updated melodic binaries as well.

**Comment by Timple** [comment]
Awesome, thanks!

**Pull request merged**
