### PR TITLE
Two and three D405 examples

### PR DESCRIPTION
**Pull request by adricort**
Since there are not well documented examples in ROS2 for multi cameras, I configured two launch codes with their respective easy-to-use rviz config files, which mainly are two examples with:
- 2 Intel RealSense D405 cameras
- 3 Intel RealSense D405 cameras
In can manage up to 4, but I only tested it with 3.
It took me some time and an open issue (it will be closed soon) in the forum to get it working in the real robotic arm that I am working on. This will help people to transfer quickly their projects.

I am using: multi cameras to create a single rgbd_image, which will help to create a synchronous MapCloud, and, so far, it is only using the odometry of the front camera.

Thanks to the team for the help, I hope the pull request can be accepted.

### CODE REVIEW

**Comment by SammyRamone** [comment]
This is the related issue https://github.com/introlab/rtabmap_ros/issues/983

**Comment by matlabbe** [comment]
As the name of the launch file is specific, could you remove all the conditional arguments, make hard-coded parameters that should be used by his example, and remove all arguments declared that are not used? Just make to most basic example like I did in the d435i example launch files: https://github.com/introlab/rtabmap_ros/tree/ros2/rtabmap_examples/launch

**Comment by adricort** [comment]
Okay, if it is to be hard-coded, then I will. Thank you for the feedback!

**Comment by adricort** [comment]
Closed in favor of https://github.com/introlab/rtabmap_ros/pull/1002, see comment there.

**Pull request closed without merging**
