### PR TITLE
Fix parameter name

### PR DESCRIPTION
**Pull request by Timple**

### CODE REVIEW

**Comment by matlabbe** [comment]
Thank you for the fix. I pushed it to ros2 base branch in the commit above. The galactic-devel branch is used to keep track of the version released on ros build farm, prefer modifying ros2 branch instead unless it is very galactic specific.

**Comment by Timple** [comment]
Alrighty, will do.

Could this fix be released as patch version for galactic? :slightly_smiling_face:

**Comment by Timple** [comment]
Alrighty, will do.

Could this fix be released as patch version for galactic? :slightly_smiling_face:

**Comment by matlabbe** [comment]
merged!

**Comment by Timple** [comment]
Thanks!

Will it be bloom-released to the buildfarm as well?

**Comment by matlabbe** [comment]
I'll check to update all packages on buildfarm somewhere before Christmas.

**Comment by matlabbe** [comment]
Here it goes: https://github.com/ros/rosdistro/pull/31609

**Pull request closed without merging**
